package dev.sandbox.lab.taskapi.domain;

import java.time.Instant;
import java.util.UUID;

// A plain mutable class, not a record - see the DTOs in the `web` package for the contrast.
// Domain entities like this one change over their lifetime (status updates below), and once
// this gets a real database behind it, a JPA entity couldn't be a record anyway: JPA needs a
// no-arg constructor and mutable, non-final fields to do its lazy-loading/proxying tricks,
// which records deliberately don't allow.
public class Task {
    private final UUID id;
    private final String title;
    private TaskStatus status;
    private final Instant createdAt;

    public Task(UUID id, String title, TaskStatus status, Instant createdAt) {
        this.id = id;
        this.title = title;
        this.status = status;
        this.createdAt = createdAt;
    }

    // No auto-properties in Java - get/set methods are the idiom C#'s `{ get; set; }` compiles
    // down to anyway, just written out by hand (or generated by an IDE/Lombok).
    public UUID getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public TaskStatus getStatus() {
        return status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void updateStatus(TaskStatus newStatus) {
        this.status = newStatus;
    }
}
